import type { QuizQuestion } from "../types";

export const agentsQuestions: QuizQuestion[] = [
  {
    id: "agent-1",
    categorySlug: "agents",
    question: "Qu'est-ce qui caractérise un sous-agent par rapport à la conversation principale ?",
    options: [
      "Il partage exactement la même fenêtre de contexte",
      "Il a sa propre fenêtre de contexte, parfois un prompt système spécialisé et des outils limités",
      "Il ne peut jamais utiliser d'outils",
      "Il remplace définitivement la session principale",
    ],
    answerIndex: 1,
    explanation: "Un sous-agent est une instance isolée avec son propre contexte, ce qui permet de protéger la conversation principale du bruit.",
    difficulty: "Facile",
  },
  {
    id: "agent-2",
    categorySlug: "agents",
    question: "Quel est l'un des principaux bénéfices de déléguer une recherche volumineuse à un sous-agent ?",
    options: [
      "Cela ralentit systématiquement la tâche",
      "Le bruit (lecture de nombreux fichiers) reste dans le sous-agent ; seul le résumé remonte à la conversation principale",
      "Cela désactive automatiquement les permissions",
      "Cela supprime le besoin de CLAUDE.md",
    ],
    answerIndex: 1,
    explanation: "Le sous-agent absorbe le détail volumineux, protégeant le contexte principal qui ne reçoit que la synthèse utile.",
    difficulty: "Moyen",
  },
  {
    id: "agent-3",
    categorySlug: "agents",
    question: "Où définit-on un sous-agent personnalisé dans un projet ?",
    options: [".claude/skills/", ".claude/agents/", ".claude/hooks/", ".claude/commands/"],
    answerIndex: 1,
    explanation: "Les sous-agents se définissent en Markdown (nom, description, outils, prompt système) dans .claude/agents/.",
    difficulty: "Facile",
  },
  {
    id: "agent-4",
    categorySlug: "agents",
    question:
      "Un nouvel appel de sous-agent a-t-il accès à la mémoire de la conversation principale en cours ?",
    options: [
      "Oui, il voit tout l'historique automatiquement",
      "Non, il démarre sans mémoire — tout le contexte nécessaire doit être inclus explicitement dans le prompt",
      "Seulement les 5 derniers messages",
      "Seulement si CLAUDE.md le précise",
    ],
    answerIndex: 1,
    explanation: "Chaque appel d'agent démarre froid, sans mémoire de la conversation : le prompt de délégation doit être autonome.",
    difficulty: "Moyen",
  },
  {
    id: "agent-5",
    categorySlug: "agents",
    question: "Quelle option permet à un sous-agent de travailler sur une copie isolée du repo (worktree) ?",
    options: ["run_in_background: true", "isolation: \"worktree\"", "model: inherit", "tools: Read"],
    answerIndex: 1,
    explanation: "isolation: \"worktree\" crée un worktree git temporaire pour que l'agent travaille sans affecter le répertoire principal.",
    difficulty: "Difficile",
  },
  {
    id: "agent-6",
    categorySlug: "agents",
    question: "Quand faut-il utiliser run_in_background pour un sous-agent ?",
    options: [
      "Quand son résultat est immédiatement nécessaire pour continuer la tâche principale",
      "Quand le travail est indépendant et que le résultat n'est pas immédiatement bloquant",
      "Jamais, c'est une option obsolète",
      "Uniquement pour les tâches de lecture de fichiers",
    ],
    answerIndex: 1,
    explanation: "run_in_background convient au travail indépendant qui peut progresser en parallèle sans bloquer la conversation principale.",
    difficulty: "Moyen",
  },
  {
    id: "agent-7",
    categorySlug: "agents",
    question: "Qu'est-ce qui caractérise un bon prompt de délégation à un sous-agent ?",
    options: [
      "Il est volontairement vague pour laisser de la liberté",
      "Il inclut l'objectif, le pourquoi, les fichiers/contraintes connus et le format de réponse attendu",
      "Il se limite à une seule phrase sans contexte",
      "Il ne doit jamais mentionner de chemins de fichiers",
    ],
    answerIndex: 1,
    explanation: "Un brief précis (objectif, contexte, contraintes, format attendu) produit un travail exploitable directement, contrairement à une consigne vague.",
    difficulty: "Moyen",
  },
  {
    id: "agent-8",
    categorySlug: "agents",
    question: "Quel champ du frontmatter d'un agent restreint les outils qu'il peut utiliser ?",
    options: ["model", "tools", "description", "name"],
    answerIndex: 1,
    explanation: "Le champ tools liste les outils disponibles pour ce sous-agent (ex: Read, Grep, Glob, Bash).",
    difficulty: "Moyen",
  },
  {
    id: "agent-9",
    categorySlug: "agents",
    question: "Pourquoi un agent « Explore » est-il souvent configuré en lecture seule ?",
    options: [
      "Parce que la lecture est plus rapide techniquement",
      "Parce que sa mission est de localiser du code, pas de le modifier — limiter ses outils réduit les risques",
      "Parce que les agents en lecture seule sont gratuits",
      "Parce que Claude Code l'impose par défaut à tous les agents",
    ],
    answerIndex: 1,
    explanation: "Restreindre un agent de recherche à la lecture évite des effets de bord non désirés alors que sa mission ne nécessite que d'explorer.",
    difficulty: "Moyen",
  },
  {
    id: "agent-10",
    categorySlug: "agents",
    question: "Quelle erreur faut-il éviter en délégant une tâche du type « corrige le bug » à un sous-agent ?",
    options: [
      "Donner trop de détails sur le bug",
      "Déléguer la compréhension du problème sans avoir partagé ce qu'on sait déjà",
      "Préciser le format de réponse attendu",
      "Donner les chemins de fichiers concernés",
    ],
    answerIndex: 1,
    explanation: "Déléguer la compréhension produit un travail générique ; il faut détailler ce qu'on sait déjà et ce qu'il reste à vérifier.",
    difficulty: "Difficile",
  },
  {
    id: "agent-11",
    categorySlug: "agents",
    question: "Quel outil de la conversation principale permet d'invoquer un sous-agent défini dans .claude/agents/ ?",
    options: ["Read", "Task / Agent (avec subagent_type)", "Glob", "WebSearch"],
    answerIndex: 1,
    explanation: "L'outil Task/Agent accepte un subagent_type correspondant au nom d'un agent défini dans .claude/agents/.",
    difficulty: "Moyen",
  },
  {
    id: "agent-12",
    categorySlug: "agents",
    question: "Plusieurs sous-agents indépendants peuvent-ils travailler simultanément ?",
    options: [
      "Non, un seul sous-agent peut être actif à la fois",
      "Oui, ils peuvent être lancés en parallèle sur des sous-tâches distinctes",
      "Seulement si CLAUDE.md le permet explicitement",
      "Seulement en mode Bypass",
    ],
    answerIndex: 1,
    explanation: "La parallélisation de sous-agents indépendants est l'un des bénéfices clés de la délégation.",
    difficulty: "Facile",
  },
];
