import type { QuizQuestion } from "../types";

export const bonnesPratiquesQuestions: QuizQuestion[] = [
  {
    id: "bp-1",
    categorySlug: "bonnes-pratiques",
    question: "Quelle pratique git est recommandée par défaut plutôt que `git commit --amend` ?",
    options: [
      "Toujours utiliser --amend pour garder un historique propre",
      "Créer un nouveau commit, sauf demande explicite d'amend",
      "Ne jamais committer plus d'une fois par jour",
      "Toujours squasher tous les commits avant de pousser",
    ],
    answerIndex: 1,
    explanation: "Un amend sur un commit déjà poussé réécrit l'historique partagé ; créer un nouveau commit est plus sûr par défaut.",
    difficulty: "Moyen",
  },
  {
    id: "bp-2",
    categorySlug: "bonnes-pratiques",
    question: "Avant de rédiger un message de commit, sur quoi Claude Code doit-il se baser ?",
    options: [
      "Une supposition générale sur le contenu du projet",
      "Le `git diff` réel des changements",
      "Le titre de la dernière issue GitHub fermée",
      "Le nombre de fichiers modifiés uniquement",
    ],
    answerIndex: 1,
    explanation: "Le message de commit doit refléter les changements réels observés dans le diff, pas une supposition.",
    difficulty: "Facile",
  },
  {
    id: "bp-3",
    categorySlug: "bonnes-pratiques",
    question: "Que faut-il faire avant tout `git push --force` sur une branche partagée comme main ?",
    options: [
      "Le faire directement, c'est une opération sans risque",
      "Obtenir une autorisation explicite, car cela peut écraser le travail d'autrui",
      "Toujours le faire en dehors des heures de bureau",
      "Le remplacer systématiquement par --no-verify",
    ],
    answerIndex: 1,
    explanation: "Un force-push sur une branche partagée est difficile à inverser et peut écraser des commits d'autres personnes : autorisation explicite requise.",
    difficulty: "Moyen",
  },
  {
    id: "bp-4",
    categorySlug: "bonnes-pratiques",
    question: "Lors du résumé d'une Pull Request, quels commits doivent être pris en compte ?",
    options: [
      "Seulement le dernier commit",
      "Tous les commits du diff par rapport à la branche de base",
      "Seulement les commits du jour",
      "Aucun, seul le titre de la PR compte",
    ],
    answerIndex: 1,
    explanation: "Un résumé fiable de PR doit analyser l'ensemble des commits inclus, pas seulement le plus récent.",
    difficulty: "Moyen",
  },
  {
    id: "bp-5",
    categorySlug: "bonnes-pratiques",
    question: "Pourquoi vérifier un changement UI dans un vrai navigateur plutôt que de se fier qu'aux tests ?",
    options: [
      "Les tests ne s'exécutent jamais correctement",
      "Les tests vérifient la correction du code, pas la correction perçue de la fonctionnalité",
      "Le navigateur est plus rapide que les tests automatisés",
      "Ce n'est pas recommandé, les tests suffisent toujours",
    ],
    answerIndex: 1,
    explanation: "Une fonctionnalité peut passer les tests tout en étant cassée du point de vue de l'expérience utilisateur réelle.",
    difficulty: "Moyen",
  },
  {
    id: "bp-6",
    categorySlug: "bonnes-pratiques",
    question: "Comment gérer efficacement une tâche large et complexe en plusieurs étapes ?",
    options: [
      "Tout faire d'un seul bloc sans suivi intermédiaire",
      "La découper en sous-étapes suivies via une todo-list (TaskCreate/TodoWrite)",
      "Ouvrir autant de sessions parallèles que d'étapes sans coordination",
      "Attendre que le contexte soit plein avant de commencer",
    ],
    answerIndex: 1,
    explanation: "Une todo-list garde une trace claire de ce qui est fait, en cours, et restant sur une tâche multi-étapes.",
    difficulty: "Facile",
  },
  {
    id: "bp-7",
    categorySlug: "bonnes-pratiques",
    question: "Que faire avant qu'une session ne devienne trop lourde en contexte ?",
    options: [
      "Attendre la coupure automatique",
      "Utiliser /compact proactivement",
      "Désinstaller et réinstaller Claude Code",
      "Changer de modèle en plein milieu de la tâche",
    ],
    answerIndex: 1,
    explanation: "Compacter proactivement évite d'attendre la limite et garde la session plus réactive.",
    difficulty: "Facile",
  },
  {
    id: "bp-8",
    categorySlug: "bonnes-pratiques",
    question: "Quelle habitude permet d'éviter de répéter la même correction à Claude Code à chaque session ?",
    options: [
      "Ne rien faire, il apprend automatiquement de chaque session",
      "Ajouter la règle corrigée à CLAUDE.md ou à la mémoire structurée",
      "Changer de modèle après chaque erreur",
      "Désactiver le mode Plan",
    ],
    answerIndex: 1,
    explanation: "Mémoriser durablement (CLAUDE.md, mémoire) une correction évite de la répéter manuellement à chaque session.",
    difficulty: "Facile",
  },
  {
    id: "bp-9",
    categorySlug: "bonnes-pratiques",
    question: "Pour une action irréversible et visible publiquement (déploiement, message envoyé), quelle attitude adopter ?",
    options: [
      "Présumer une autorisation tacite si le contexte semble favorable",
      "Toujours confirmer explicitement avec l'utilisateur avant d'agir",
      "Agir immédiatement pour gagner du temps",
      "Déléguer systématiquement à un sous-agent sans confirmation",
    ],
    answerIndex: 1,
    explanation: "Sur les actions irréversibles ou publiques, l'humain doit rester dans la boucle via une confirmation explicite, jamais présumée.",
    difficulty: "Moyen",
  },
  {
    id: "bp-10",
    categorySlug: "bonnes-pratiques",
    question: "Que doit-on faire avant de merger un changement assisté par Claude Code ?",
    options: [
      "Rien de spécial si le code compile",
      "Lancer une revue (/review ou sous-agent) et les tests, voire ajouter des tests manquants",
      "Supprimer l'historique de commits",
      "Désactiver temporairement la CI",
    ],
    answerIndex: 1,
    explanation: "Une revue ciblée et l'exécution des tests (avec ajout si nécessaire) sont recommandées avant de merger.",
    difficulty: "Facile",
  },
  {
    id: "bp-11",
    categorySlug: "bonnes-pratiques",
    question: "Pourquoi donner le « pourquoi » d'une tâche, pas seulement le « quoi », améliore les résultats ?",
    options: [
      "Cela n'a aucun impact sur la qualité du résultat",
      "Cela permet à Claude Code de prendre de meilleures décisions alignées sur l'objectif réel",
      "Cela ralentit systématiquement l'exécution",
      "Cela désactive certains outils par sécurité",
    ],
    answerIndex: 1,
    explanation: "Comprendre l'objectif réel permet à l'agent de faire des choix pertinents même face à des cas non explicitement couverts par la consigne.",
    difficulty: "Moyen",
  },
  {
    id: "bp-12",
    categorySlug: "bonnes-pratiques",
    question: "Quelle est la meilleure pratique pour des recherches volumineuses sur un gros repo ?",
    options: [
      "Tout lire directement dans la conversation principale",
      "Déléguer la recherche à un sous-agent pour ne pas saturer le contexte principal",
      "Ignorer la recherche et deviner la réponse",
      "Désactiver Grep et Glob pour forcer une approche manuelle",
    ],
    answerIndex: 1,
    explanation: "Déléguer les recherches volumineuses à un sous-agent protège le contexte principal du détail inutile.",
    difficulty: "Moyen",
  },
];
