import type { QuizQuestion } from "../types";

export const claudeMdMemoireQuestions: QuizQuestion[] = [
  {
    id: "mem-1",
    categorySlug: "claude-md-memoire",
    question: "Quel fichier représente la mémoire « utilisateur », valable sur tous les projets ?",
    options: ["./CLAUDE.md", "~/.claude/CLAUDE.md", "./CLAUDE.local.md", ".claude/settings.json"],
    answerIndex: 1,
    explanation: "~/.claude/CLAUDE.md contient les préférences valables sur tous vos projets, indépendamment du repo courant.",
    difficulty: "Moyen",
  },
  {
    id: "mem-2",
    categorySlug: "claude-md-memoire",
    question: "Quel fichier de mémoire projet n'est PAS commité avec l'équipe ?",
    options: ["CLAUDE.md", "CLAUDE.local.md", "README.md", ".claude/agents/reviewer.md"],
    answerIndex: 1,
    explanation: "CLAUDE.local.md contient des préférences personnelles sur ce projet, non commitées (gitignored).",
    difficulty: "Moyen",
  },
  {
    id: "mem-3",
    categorySlug: "claude-md-memoire",
    question: "Quel raccourci dans le REPL permet d'ajouter rapidement une instruction à la mémoire sans éditer le fichier à la main ?",
    options: ["Préfixer le message avec #", "Préfixer le message avec !", "Préfixer le message avec /", "Appuyer sur Ctrl+M"],
    answerIndex: 0,
    explanation: "Le préfixe # en début de message ajoute rapidement une instruction à la mémoire.",
    difficulty: "Difficile",
  },
  {
    id: "mem-4",
    categorySlug: "claude-md-memoire",
    question: "Quelle est la bonne pratique principale concernant le contenu de CLAUDE.md ?",
    options: [
      "Documenter exhaustivement chaque fonction du code",
      "Rester concis et actionnable, documenter le pourquoi quand c'est contre-intuitif",
      "Y mettre uniquement des liens vers la documentation externe",
      "Le générer une seule fois et ne plus jamais le modifier",
    ],
    answerIndex: 1,
    explanation: "Une liste claire et actionnable vaut mieux qu'un essai ; le code déductible n'a pas besoin d'être réécrit dans CLAUDE.md.",
    difficulty: "Moyen",
  },
  {
    id: "mem-5",
    categorySlug: "claude-md-memoire",
    question: "Dans un monorepo, à quoi sert un CLAUDE.md placé dans un sous-dossier spécifique ?",
    options: [
      "Il remplace totalement le CLAUDE.md racine",
      "Il fournit un contexte spécifique à ce module/package",
      "Il n'a aucun effet, seul le fichier racine est lu",
      "Il sert uniquement à des fins de documentation, jamais chargé par Claude Code",
    ],
    answerIndex: 1,
    explanation: "Un CLAUDE.md de sous-dossier complète la hiérarchie de mémoire avec un contexte propre à ce module.",
    difficulty: "Moyen",
  },
  {
    id: "mem-6",
    categorySlug: "claude-md-memoire",
    question: "Que se passe-t-il quand vous corrigez Claude Code en session sur une approche erronée ?",
    options: [
      "Rien, la correction ne sert que pour la session en cours",
      "Il est recommandé de mettre à jour CLAUDE.md pour éviter de répéter la correction",
      "Claude Code modifie automatiquement son modèle sous-jacent",
      "La correction est seulement valable si elle est répétée 3 fois",
    ],
    answerIndex: 1,
    explanation: "Mettre à jour CLAUDE.md (ou la mémoire structurée) après une correction évite de la répéter à chaque session.",
    difficulty: "Moyen",
  },
  {
    id: "mem-7",
    categorySlug: "claude-md-memoire",
    question: "En cas de conflit entre deux niveaux de mémoire, lequel a généralement la priorité ?",
    options: [
      "Le niveau le plus général (utilisateur)",
      "Le niveau le plus proche du travail en cours (ex: sous-dossier)",
      "Toujours CLAUDE.md racine, jamais les autres",
      "Le fichier créé le plus récemment, peu importe le niveau",
    ],
    answerIndex: 1,
    explanation: "Plus un fichier de mémoire est proche du contexte de travail, plus son contenu est pertinent et prioritaire.",
    difficulty: "Difficile",
  },
  {
    id: "mem-8",
    categorySlug: "claude-md-memoire",
    question: "En quoi la mémoire structurée gérée par l'agent diffère-t-elle de CLAUDE.md ?",
    options: [
      "Elle est identique, ce sont juste deux noms pour le même mécanisme",
      "Elle est éditée et mise à jour activement par l'agent lui-même, plutôt qu'à la main",
      "Elle ne peut contenir que du code, jamais de texte libre",
      "Elle est toujours partagée publiquement sur GitHub",
    ],
    answerIndex: 1,
    explanation: "La mémoire structurée est gérée par l'agent, qui la met à jour quand des faits durables ou des retours utilisateurs émergent, contrairement à CLAUDE.md édité manuellement.",
    difficulty: "Difficile",
  },
  {
    id: "mem-9",
    categorySlug: "claude-md-memoire",
    question: "Quelle commande génère automatiquement un premier CLAUDE.md à partir de l'analyse du repo ?",
    options: ["/memory", "/init", "/generate", "/scaffold"],
    answerIndex: 1,
    explanation: "/init analyse package.json, la structure de dossiers, le README, etc. pour produire un CLAUDE.md initial.",
    difficulty: "Facile",
  },
  {
    id: "mem-10",
    categorySlug: "claude-md-memoire",
    question: "Lequel de ces contenus est le PLUS pertinent à inclure dans CLAUDE.md ?",
    options: [
      "La liste exhaustive de tous les fichiers du projet",
      "La règle « ne jamais modifier le dossier legacy/ sans validation explicite »",
      "Le contenu complet de la documentation de React",
      "L'historique complet des commits git",
    ],
    answerIndex: 1,
    explanation: "CLAUDE.md doit capturer ce qui n'est pas évident à la simple lecture du code : règles, contraintes, pièges connus.",
    difficulty: "Facile",
  },
  {
    id: "mem-11",
    categorySlug: "claude-md-memoire",
    question: "Quel est le principal avantage de documenter le « pourquoi » d'une règle dans CLAUDE.md ?",
    options: [
      "Cela n'apporte aucun avantage particulier",
      "Cela aide l'agent à juger correctement les cas limites non explicitement couverts par la règle",
      "Cela réduit la taille du fichier",
      "Cela empêche toute modification future de la règle",
    ],
    answerIndex: 1,
    explanation: "Connaître le pourquoi permet à l'agent (et aux humains) d'extrapoler correctement face à des cas limites non prévus explicitement.",
    difficulty: "Moyen",
  },
  {
    id: "mem-12",
    categorySlug: "claude-md-memoire",
    question: "Quel ordre de chargement de la mémoire est correct, du plus général au plus spécifique ?",
    options: [
      "Projet → utilisateur → local → sous-dossier",
      "Utilisateur → projet → local → sous-dossier",
      "Sous-dossier → local → projet → utilisateur",
      "Local → utilisateur → sous-dossier → projet",
    ],
    answerIndex: 1,
    explanation: "L'ordre va du plus général (utilisateur, valable partout) au plus spécifique (sous-dossier d'un module particulier).",
    difficulty: "Moyen",
  },
];
