import type { QuizQuestion } from "../types";

export const cliReplQuestions: QuizQuestion[] = [
  {
    id: "repl-1",
    categorySlug: "cli-repl",
    question: "Quelle commande slash vide complètement l'historique de conversation ?",
    options: ["/compact", "/clear", "/reset", "/new"],
    answerIndex: 1,
    explanation: "/clear repart de zéro, sans résumé, contrairement à /compact qui préserve un résumé.",
    difficulty: "Facile",
  },
  {
    id: "repl-2",
    categorySlug: "cli-repl",
    question: "Quelle commande slash résume la conversation pour libérer du contexte sans tout perdre ?",
    options: ["/clear", "/compact", "/summary", "/trim"],
    answerIndex: 1,
    explanation: "/compact demande à Claude de résumer la conversation en gardant l'essentiel, puis continue avec un contexte allégé.",
    difficulty: "Facile",
  },
  {
    id: "repl-3",
    categorySlug: "cli-repl",
    question: "Quel raccourci clavier permet de changer de mode de permission sans relancer la session ?",
    options: ["Ctrl+P", "Shift+Tab", "Alt+M", "Ctrl+Shift+P"],
    answerIndex: 1,
    explanation: "Shift+Tab bascule entre les modes (normal, auto-accept, plan) directement dans le REPL.",
    difficulty: "Moyen",
  },
  {
    id: "repl-4",
    categorySlug: "cli-repl",
    question: "Que fait le symbole `!` en début de message dans le REPL ?",
    options: [
      "Marque le message comme urgent/prioritaire",
      "Exécute directement une commande shell dans le contexte de la session",
      "Active le mode debug",
      "Annule le dernier message envoyé",
    ],
    answerIndex: 1,
    explanation: "Le préfixe ! exécute une commande shell directement, utile pour des commandes interactives comme une authentification.",
    difficulty: "Moyen",
  },
  {
    id: "repl-5",
    categorySlug: "cli-repl",
    question: "Où place-t-on un fichier Markdown pour créer une commande slash personnalisée comme `/release` ?",
    options: [".claude/skills/release.md", ".claude/commands/release.md", ".claude/agents/release.md", "release.command.md"],
    answerIndex: 1,
    explanation: "Les commandes slash personnalisées sont des fichiers Markdown dans .claude/commands/.",
    difficulty: "Moyen",
  },
  {
    id: "repl-6",
    categorySlug: "cli-repl",
    question: "Quelle commande affiche le coût/nombre de tokens consommés sur la session en cours ?",
    options: ["/usage", "/cost", "/tokens", "/billing"],
    answerIndex: 1,
    explanation: "/cost affiche le coût et la consommation de tokens de la session.",
    difficulty: "Facile",
  },
  {
    id: "repl-7",
    categorySlug: "cli-repl",
    question: "Quelle commande permet d'éditer la mémoire (CLAUDE.md) directement depuis le REPL ?",
    options: ["/memory", "/edit-memory", "/claude-md", "/context"],
    answerIndex: 0,
    explanation: "/memory ouvre l'édition de la mémoire directement, sans quitter la session.",
    difficulty: "Moyen",
  },
  {
    id: "repl-8",
    categorySlug: "cli-repl",
    question:
      "Une commande slash personnalisée peut accepter des arguments. Quelle variable les représente dans le fichier Markdown ?",
    options: ["$INPUT", "$ARGUMENTS", "$PARAMS", "{{args}}"],
    answerIndex: 1,
    explanation: "$ARGUMENTS représente les arguments passés après la commande slash dans le fichier de définition.",
    difficulty: "Difficile",
  },
  {
    id: "repl-9",
    categorySlug: "cli-repl",
    question: "Que se passe-t-il si le contexte se remplit fortement sans intervention de l'utilisateur ?",
    options: [
      "La session plante immédiatement",
      "Claude Code peut auto-compacter automatiquement pour éviter de couper la conversation",
      "Toutes les commandes slash sont désactivées",
      "Le modèle change automatiquement pour un modèle moins coûteux",
    ],
    answerIndex: 1,
    explanation: "Au-delà d'un certain remplissage, l'auto-compactage évite que la conversation soit brutalement coupée.",
    difficulty: "Moyen",
  },
  {
    id: "repl-10",
    categorySlug: "cli-repl",
    question: "Quelle commande liste toutes les commandes slash disponibles ?",
    options: ["/list", "/commands", "/help", "/?"],
    answerIndex: 2,
    explanation: "/help liste les commandes disponibles dans la session.",
    difficulty: "Facile",
  },
  {
    id: "repl-11",
    categorySlug: "cli-repl",
    question: "Quelle commande gère les sous-agents disponibles dans le projet ?",
    options: ["/subagents", "/agents", "/delegate", "/bots"],
    answerIndex: 1,
    explanation: "/agents permet de gérer (lister, créer, modifier) les sous-agents disponibles.",
    difficulty: "Facile",
  },
  {
    id: "repl-12",
    categorySlug: "cli-repl",
    question: "Pourquoi préférer /compact à /clear entre deux étapes d'une même tâche complexe ?",
    options: [
      "/compact est plus rapide à exécuter",
      "/compact garde les décisions et le travail en cours sous forme résumée, /clear perd tout",
      "/clear ne fonctionne que pour les fichiers texte",
      "Il n'y a aucune différence fonctionnelle entre les deux",
    ],
    answerIndex: 1,
    explanation: "/compact résume en préservant l'essentiel du contexte utile, contrairement à /clear qui efface tout sans résumé.",
    difficulty: "Moyen",
  },
];
