import type { QuizQuestion } from "../types";

export const hooksQuestions: QuizQuestion[] = [
  {
    id: "hook-1",
    categorySlug: "hooks",
    question: "Quel est le principal avantage des hooks par rapport à une simple instruction dans CLAUDE.md ?",
    options: [
      "Les hooks sont plus rapides à écrire",
      "Les hooks imposent un comportement déterministe, non soumis à l'interprétation du modèle",
      "Les hooks ne nécessitent aucune configuration",
      "Les hooks remplacent complètement les permissions",
    ],
    answerIndex: 1,
    explanation: "Un hook exécute toujours la même commande shell dans les mêmes conditions, sans dépendre de l'interprétation du modèle.",
    difficulty: "Moyen",
  },
  {
    id: "hook-2",
    categorySlug: "hooks",
    question: "Quel événement de hook permet de bloquer un appel d'outil avant qu'il ne s'exécute ?",
    options: ["PostToolUse", "PreToolUse", "SessionStart", "Notification"],
    answerIndex: 1,
    explanation: "PreToolUse se déclenche avant l'exécution d'un outil et peut empêcher l'appel.",
    difficulty: "Facile",
  },
  {
    id: "hook-3",
    categorySlug: "hooks",
    question: "Quel événement de hook est adapté pour reformater automatiquement un fichier après une édition ?",
    options: ["PreToolUse", "PostToolUse", "UserPromptSubmit", "Stop"],
    answerIndex: 1,
    explanation: "PostToolUse se déclenche après l'exécution de l'outil (ici Edit/Write) et peut réagir, par exemple en lançant Prettier.",
    difficulty: "Facile",
  },
  {
    id: "hook-4",
    categorySlug: "hooks",
    question: "Quel événement se déclenche à chaque message envoyé par l'utilisateur ?",
    options: ["SessionStart", "UserPromptSubmit", "Stop", "PreToolUse"],
    answerIndex: 1,
    explanation: "UserPromptSubmit se déclenche quand l'utilisateur soumet un message.",
    difficulty: "Facile",
  },
  {
    id: "hook-5",
    categorySlug: "hooks",
    question: "Avec quelles permissions un hook s'exécute-t-il ?",
    options: [
      "Avec des permissions restreintes spécifiques aux hooks",
      "Avec les permissions de l'utilisateur système",
      "Toujours en lecture seule",
      "Avec les permissions du compte Anthropic uniquement",
    ],
    answerIndex: 1,
    explanation: "Les hooks tournent avec les permissions système de l'utilisateur, donc ils doivent être audités comme du code de production.",
    difficulty: "Difficile",
  },
  {
    id: "hook-6",
    categorySlug: "hooks",
    question: "Dans `.claude/settings.json`, quel champ identifie quel(s) outil(s) déclenche(nt) un hook PostToolUse ?",
    options: ["trigger", "matcher", "filter", "selector"],
    answerIndex: 1,
    explanation: "Le champ matcher (ex: \"Edit|Write\") précise quels outils déclenchent le hook.",
    difficulty: "Moyen",
  },
  {
    id: "hook-7",
    categorySlug: "hooks",
    question: "Comment un hook PreToolUse signale-t-il qu'il faut bloquer l'action ?",
    options: [
      "En renvoyant toujours un code de sortie 0",
      "Avec un code de sortie non nul ou une sortie JSON {\"decision\":\"block\"}",
      "En écrivant un fichier .block à la racine",
      "Il est impossible pour un hook de bloquer une action",
    ],
    answerIndex: 1,
    explanation: "Un code de sortie non nul (ou une réponse JSON explicite de blocage) empêche l'outil de s'exécuter.",
    difficulty: "Difficile",
  },
  {
    id: "hook-8",
    categorySlug: "hooks",
    question: "Quel événement se déclenche au tout début d'une nouvelle session Claude Code ?",
    options: ["Stop", "SessionStart", "PostToolUse", "Notification"],
    answerIndex: 1,
    explanation: "SessionStart se déclenche au démarrage de la session, utile pour charger un contexte ou afficher des informations.",
    difficulty: "Facile",
  },
  {
    id: "hook-9",
    categorySlug: "hooks",
    question: "Quel risque existe si un hook est mal écrit ?",
    options: [
      "Aucun risque, les hooks sont toujours sans danger",
      "Il peut bloquer ou casser des actions légitimes",
      "Il ralentit uniquement l'affichage visuel",
      "Il désactive automatiquement Claude Code",
    ],
    answerIndex: 1,
    explanation: "Un hook mal écrit peut bloquer à tort des actions légitimes ou avoir des effets de bord destructeurs, comme tout script shell.",
    difficulty: "Moyen",
  },
  {
    id: "hook-10",
    categorySlug: "hooks",
    question: "Quel cas d'usage est le PLUS adapté à un hook plutôt qu'à une simple règle dans CLAUDE.md ?",
    options: [
      "Expliquer l'architecture générale du projet",
      "Garantir que chaque fichier modifié est systématiquement reformaté par Prettier",
      "Décrire les conventions de nommage des variables",
      "Lister les commandes de build disponibles",
    ],
    answerIndex: 1,
    explanation: "Garantir un formatage systématique est un comportement déterministe à imposer sans dépendre de l'interprétation du modèle — un cas d'usage typique de hook.",
    difficulty: "Moyen",
  },
  {
    id: "hook-11",
    categorySlug: "hooks",
    question: "Quel événement permet de réagir à la fin d'une session Claude Code ?",
    options: ["SessionEnd", "Stop", "PostToolUse", "UserPromptSubmit"],
    answerIndex: 0,
    explanation: "SessionEnd se déclenche à la fin de la session, par opposition à Stop qui se déclenche quand l'agent termine sa réponse.",
    difficulty: "Moyen",
  },
  {
    id: "hook-12",
    categorySlug: "hooks",
    question: "Quelle variable d'environnement contient typiquement les chemins de fichiers concernés par un hook PostToolUse sur Edit/Write ?",
    options: ["$CLAUDE_FILE_PATHS", "$EDITED_FILES", "$TOOL_OUTPUT", "$CLAUDE_PATH"],
    answerIndex: 0,
    explanation: "$CLAUDE_FILE_PATHS expose les fichiers concernés, ce qui permet par exemple de les passer à un formateur.",
    difficulty: "Difficile",
  },
];
