import type { QuizQuestion } from "../types";

export const mcpQuestions: QuizQuestion[] = [
  {
    id: "mcp-1",
    categorySlug: "mcp",
    question: "Que signifie l'acronyme MCP ?",
    options: [
      "Model Context Protocol",
      "Multi-Client Processing",
      "Managed Connection Pool",
      "Model Configuration Package",
    ],
    answerIndex: 0,
    explanation: "MCP signifie Model Context Protocol, un protocole ouvert standardisé par Anthropic.",
    difficulty: "Facile",
  },
  {
    id: "mcp-2",
    categorySlug: "mcp",
    question: "Quel problème MCP résout-il principalement ?",
    options: [
      "Le besoin de code d'intégration sur-mesure pour chaque outil externe",
      "La lenteur des modèles de langage",
      "Le manque de mémoire des agents",
      "La gestion des conflits git",
    ],
    answerIndex: 0,
    explanation: "MCP standardise la connexion entre agents et outils externes, évitant une intégration sur-mesure pour chaque service.",
    difficulty: "Moyen",
  },
  {
    id: "mcp-3",
    categorySlug: "mcp",
    question: "Quelles sont les trois primitives définies par MCP ?",
    options: [
      "Tools, Resources, Prompts",
      "Functions, Variables, Constants",
      "Servers, Clients, Routers",
      "Models, Agents, Hooks",
    ],
    answerIndex: 0,
    explanation: "MCP définit Tools (actions), Resources (données lisibles) et Prompts (templates réutilisables).",
    difficulty: "Moyen",
  },
  {
    id: "mcp-4",
    categorySlug: "mcp",
    question: "Comment apparaissent les outils MCP dans Claude Code ?",
    options: [
      "Sans aucun préfixe particulier",
      "Préfixés par le nom du serveur, ex: mcp__github__create_issue",
      "Toujours en majuscules",
      "Sous forme de commandes slash uniquement",
    ],
    answerIndex: 1,
    explanation: "Les outils exposés par un serveur MCP sont préfixés par mcp__nomduserveur__nomdeloutil.",
    difficulty: "Moyen",
  },
  {
    id: "mcp-5",
    categorySlug: "mcp",
    question: "Quelle commande CLI ajoute un serveur MCP à Claude Code ?",
    options: ["claude mcp add", "claude install mcp", "claude connect", "claude server add"],
    answerIndex: 0,
    explanation: "`claude mcp add <nom> -- <commande>` enregistre un nouveau serveur MCP.",
    difficulty: "Moyen",
  },
  {
    id: "mcp-6",
    categorySlug: "mcp",
    question: "Quels sont les deux modes de transport possibles pour un serveur MCP ?",
    options: [
      "FTP et SMTP",
      "Local (stdio) et distant (HTTP/SSE)",
      "Bluetooth et WebSocket uniquement",
      "GraphQL et REST",
    ],
    answerIndex: 1,
    explanation: "Un serveur MCP peut tourner en process local via stdio, ou être hébergé à distance via HTTP/SSE.",
    difficulty: "Moyen",
  },
  {
    id: "mcp-7",
    categorySlug: "mcp",
    question: "Quel est le principal risque de sécurité lié à l'installation d'un serveur MCP non fiable ?",
    options: [
      "Une légère augmentation du temps de réponse",
      "L'exfiltration de données ou l'exécution d'actions non désirées",
      "Une incompatibilité avec les commandes slash",
      "Un coût plus élevé uniquement",
    ],
    answerIndex: 1,
    explanation: "Un serveur MCP malveillant agit avec les permissions qui lui sont accordées : il peut exfiltrer des données ou agir de façon nuisible.",
    difficulty: "Moyen",
  },
  {
    id: "mcp-8",
    categorySlug: "mcp",
    question: "Quelle commande liste les serveurs MCP actuellement connectés ?",
    options: ["claude mcp list", "claude mcp status", "claude --servers", "claude show mcp"],
    answerIndex: 0,
    explanation: "`claude mcp list` permet de vérifier régulièrement quels serveurs sont connectés et de retirer ceux inutilisés.",
    difficulty: "Moyen",
  },
  {
    id: "mcp-9",
    categorySlug: "mcp",
    question: "Pour des données externes très volumineuses, quelle approche est recommandée côté serveur MCP ?",
    options: [
      "Tout charger d'un coup dans le contexte du modèle",
      "Paginer/filtrer côté serveur avant de renvoyer les données",
      "Convertir systématiquement en images",
      "Désactiver la primitive Resources",
    ],
    answerIndex: 1,
    explanation: "Paginer/filtrer côté serveur évite de saturer le contexte du modèle avec des données non pertinentes.",
    difficulty: "Difficile",
  },
  {
    id: "mcp-10",
    categorySlug: "mcp",
    question: "Dans quel(s) fichier(s) peut-on configurer des serveurs MCP pour un projet ?",
    options: [
      "Uniquement via une interface web",
      ".mcp.json ou .claude/settings.json",
      "package.json uniquement",
      "Impossible de configurer via fichier, uniquement par CLI interactive",
    ],
    answerIndex: 1,
    explanation: "La configuration MCP peut être déclarée dans .mcp.json ou intégrée à .claude/settings.json.",
    difficulty: "Moyen",
  },
  {
    id: "mcp-11",
    categorySlug: "mcp",
    question: "Quelle analogie illustre bien le rôle de MCP pour les agents IA ?",
    options: [
      "Un pare-feu réseau",
      "Un port USB standard, branchable sur n'importe quel client compatible",
      "Un compilateur de code",
      "Un système de fichiers distribué",
    ],
    answerIndex: 1,
    explanation: "Comme un port USB, un serveur MCP écrit une fois peut être branché sur n'importe quel client compatible (Claude Code, Claude Desktop...).",
    difficulty: "Facile",
  },
  {
    id: "mcp-12",
    categorySlug: "mcp",
    question: "Quelle primitive MCP correspond à un template de prompt réutilisable fourni par le serveur ?",
    options: ["Tools", "Resources", "Prompts", "Hooks"],
    answerIndex: 2,
    explanation: "La primitive Prompts fournit des templates de prompts réutilisables, similaires à des snippets préconfigurés.",
    difficulty: "Moyen",
  },
];
