import type { QuizQuestion } from "../types";

export const outilsQuestions: QuizQuestion[] = [
  {
    id: "tool-1",
    categorySlug: "outils",
    question: "Quel outil est privilégié pour modifier une partie précise d'un fichier existant ?",
    options: ["Write", "Edit", "Bash", "Glob"],
    answerIndex: 1,
    explanation: "Edit fait un remplacement ciblé d'une chaîne unique, ce qui limite le risque d'effacer du contenu non lié et produit un diff plus lisible.",
    difficulty: "Facile",
  },
  {
    id: "tool-2",
    categorySlug: "outils",
    question: "Quel outil sert à trouver des fichiers par motif, comme tous les fichiers de test ?",
    options: ["Grep", "Glob", "Read", "Bash"],
    answerIndex: 1,
    explanation: "Glob répond à « quels fichiers correspondent à ce motif » (ex: **/*.test.ts).",
    difficulty: "Facile",
  },
  {
    id: "tool-3",
    categorySlug: "outils",
    question: "Quel outil sert à rechercher du texte ou une regex dans le contenu des fichiers ?",
    options: ["Glob", "Grep", "Write", "Read"],
    answerIndex: 1,
    explanation: "Grep (basé sur ripgrep) recherche du contenu/texte dans les fichiers, contrairement à Glob qui filtre par nom de fichier.",
    difficulty: "Facile",
  },
  {
    id: "tool-4",
    categorySlug: "outils",
    question: "Pourquoi Write est-il plus risqué qu'Edit sur un fichier déjà existant ?",
    options: [
      "Write est plus lent à exécuter",
      "Write réécrit le fichier entier, risquant d'effacer du contenu non lié à la tâche",
      "Write ne fonctionne que sur des fichiers binaires",
      "Write nécessite une connexion internet",
    ],
    answerIndex: 1,
    explanation: "Write réécrit l'intégralité du fichier, ce qui peut accidentellement supprimer du contenu si le nouveau contenu n'est pas complet.",
    difficulty: "Moyen",
  },
  {
    id: "tool-5",
    categorySlug: "outils",
    question: "Quel outil permet d'exécuter des commandes shell comme les tests ou le build ?",
    options: ["Bash", "Read", "Edit", "WebFetch"],
    answerIndex: 0,
    explanation: "Bash exécute des commandes shell, du lancement de tests à des opérations git.",
    difficulty: "Facile",
  },
  {
    id: "tool-6",
    categorySlug: "outils",
    question: "Quel type de commande Bash est considéré comme généralement sûr, sans confirmation poussée ?",
    options: [
      "git push --force",
      "rm -rf node_modules/../..",
      "git status / git diff / tests en lecture",
      "Modification de permissions système globales",
    ],
    answerIndex: 2,
    explanation: "Les commandes en lecture (status, diff, log, lancement de tests) ne modifient rien et sont généralement sûres.",
    difficulty: "Moyen",
  },
  {
    id: "tool-7",
    categorySlug: "outils",
    question: "Quel outil permet de déléguer une sous-tâche à un agent spécialisé ?",
    options: ["TodoWrite", "Task / Agent", "WebSearch", "Glob"],
    answerIndex: 1,
    explanation: "L'outil Task/Agent lance un sous-agent pour traiter une sous-tâche de façon autonome.",
    difficulty: "Moyen",
  },
  {
    id: "tool-8",
    categorySlug: "outils",
    question: "À quoi sert l'outil TodoWrite / TaskCreate ?",
    options: [
      "Exécuter des commandes shell en arrière-plan",
      "Suivre une liste de tâches pour les travaux multi-étapes",
      "Envoyer des notifications Slack",
      "Compiler le code TypeScript",
    ],
    answerIndex: 1,
    explanation: "TodoWrite/TaskCreate gère une liste de tâches pour garder une trace claire d'un travail en plusieurs étapes.",
    difficulty: "Facile",
  },
  {
    id: "tool-9",
    categorySlug: "outils",
    question: "Comment Claude Code explore-t-il un repo inconnu sans index préconstruit ?",
    options: [
      "Il télécharge l'intégralité du repo en mémoire",
      "Il combine Glob (quels fichiers) et Grep (quel contenu) pour explorer à la demande",
      "Il demande systématiquement à l'utilisateur de lister les fichiers pertinents",
      "Il refuse de travailler sans index préconstruit",
    ],
    answerIndex: 1,
    explanation: "Glob et Grep combinés permettent une exploration dynamique adaptée à des repos de toute taille.",
    difficulty: "Moyen",
  },
  {
    id: "tool-10",
    categorySlug: "outils",
    question: "Quel mécanisme peut intercepter et bloquer une commande Bash avant son exécution ?",
    options: ["Une Skill", "Un Hook PreToolUse", "Un sous-agent", "CLAUDE.md"],
    answerIndex: 1,
    explanation: "Un hook PreToolUse s'exécute avant l'appel d'un outil et peut le bloquer (ex: empêcher un force-push).",
    difficulty: "Moyen",
  },
  {
    id: "tool-11",
    categorySlug: "outils",
    question: "Quel outil permet de récupérer le contenu d'une page web ou de faire une recherche en ligne ?",
    options: ["Bash", "WebFetch / WebSearch", "Read", "Grep"],
    answerIndex: 1,
    explanation: "WebFetch récupère une page web, WebSearch effectue une recherche en ligne.",
    difficulty: "Facile",
  },
  {
    id: "tool-12",
    categorySlug: "outils",
    question:
      "Vous demandez de renommer une variable utilisée 20 fois dans un fichier. Quel outil/option est le plus adapté ?",
    options: ["Write, en réécrivant tout le fichier à la main", "Edit avec l'option replace_all", "Bash avec sed uniquement", "Glob"],
    answerIndex: 1,
    explanation: "Edit avec replace_all remplace toutes les occurrences en une seule opération ciblée, sans réécrire le fichier entier.",
    difficulty: "Moyen",
  },
];
