import type { QuizQuestion } from "../types";

export const permissionsQuestions: QuizQuestion[] = [
  {
    id: "perm-1",
    categorySlug: "permissions",
    question: "Quel mode de permission demande une confirmation pour chaque action sensible ?",
    options: ["Bypass", "Plan Mode", "Normal (par défaut)", "Auto-accept edits"],
    answerIndex: 2,
    explanation: "Le mode Normal (par défaut) confirme chaque édition de fichier et chaque commande shell sensible.",
    difficulty: "Facile",
  },
  {
    id: "perm-2",
    categorySlug: "permissions",
    question: "Dans le mode « Auto-accept edits », que se passe-t-il pour les commandes shell sensibles ?",
    options: [
      "Elles sont toutes acceptées automatiquement",
      "Elles restent confirmées par l'utilisateur",
      "Elles sont systématiquement bloquées",
      "Elles ne peuvent plus être exécutées du tout",
    ],
    answerIndex: 1,
    explanation: "Auto-accept edits n'automatise que les éditions de fichiers ; les commandes shell sensibles restent confirmées.",
    difficulty: "Moyen",
  },
  {
    id: "perm-3",
    categorySlug: "permissions",
    question: "Quel fichier contient des règles de permission allow/deny appliquées avant toute décision du modèle ?",
    options: ["CLAUDE.md", ".claude/settings.json", ".env", "package.json"],
    answerIndex: 1,
    explanation: "settings.json (ou settings.local.json) définit des règles allow/deny qui s'appliquent en amont, indépendamment du modèle.",
    difficulty: "Moyen",
  },
  {
    id: "perm-4",
    categorySlug: "permissions",
    question: "Une commande est listée dans `deny` dans settings.json. Que se passe-t-il si Claude Code propose cette commande ?",
    options: [
      "Elle est exécutée car le modèle a priorité sur la configuration",
      "Elle n'est jamais exécutée, même si le modèle le proposait",
      "Une alerte est envoyée mais la commande s'exécute",
      "Cela dépend du mode de permission actif",
    ],
    answerIndex: 1,
    explanation: "Une règle deny explicite bloque la commande avant toute exécution, peu importe ce que le modèle propose.",
    difficulty: "Moyen",
  },
  {
    id: "perm-5",
    categorySlug: "permissions",
    question: "Quel mode ne modifie aucun fichier et se contente de proposer un plan ?",
    options: ["Normal", "Auto-accept edits", "Plan Mode", "Bypass"],
    answerIndex: 2,
    explanation: "Le Plan Mode lit et analyse, mais désactive Edit/Write jusqu'à validation explicite du plan.",
    difficulty: "Facile",
  },
  {
    id: "perm-6",
    categorySlug: "permissions",
    question: "Pourquoi le mode Bypass (« YOLO ») est-il déconseillé hors environnement isolé ?",
    options: [
      "Il est beaucoup plus lent que les autres modes",
      "Il désactive toutes les confirmations, augmentant le risque d'actions irréversibles ou destructrices",
      "Il empêche l'utilisation de Git",
      "Il consomme deux fois plus de tokens",
    ],
    answerIndex: 1,
    explanation: "Sans confirmations, une action destructrice (rm -rf, force-push...) peut s'exécuter sans filet de sécurité.",
    difficulty: "Moyen",
  },
  {
    id: "perm-7",
    categorySlug: "permissions",
    question: "Quelle est la bonne attitude face à un hook de sécurité qui bloque une action ?",
    options: [
      "Toujours utiliser --no-verify pour continuer rapidement",
      "Comprendre la cause racine du blocage plutôt que de le bypasser",
      "Supprimer le hook définitivement",
      "Changer immédiatement de mode de permission vers Bypass",
    ],
    answerIndex: 1,
    explanation: "Un blocage signale souvent un vrai problème ; il faut comprendre pourquoi plutôt que de contourner la vérification.",
    difficulty: "Moyen",
  },
  {
    id: "perm-8",
    categorySlug: "permissions",
    question: "Quel principe de sécurité s'applique aux tokens fournis à des serveurs MCP ou intégrations externes ?",
    options: [
      "Toujours donner un accès admin complet pour éviter les erreurs de permission",
      "Le principe du moindre privilège : limiter le scope au strict nécessaire",
      "Partager le même token pour tous les services",
      "Aucun principe particulier ne s'applique",
    ],
    answerIndex: 1,
    explanation: "Limiter les scopes/tokens réduit l'impact en cas de compromission ou de mauvais comportement d'un outil externe.",
    difficulty: "Moyen",
  },
  {
    id: "perm-9",
    categorySlug: "permissions",
    question: "Quel mécanisme permet de tester des commandes risquées sans affecter l'environnement principal ?",
    options: [
      "Le mode Auto-accept",
      "Un environnement isolé (conteneur, VM, worktree git séparé)",
      "Une commande slash personnalisée",
      "Le mode Plan",
    ],
    answerIndex: 1,
    explanation: "Un environnement jetable (conteneur, VM, worktree) permet d'autoriser des actions plus larges sans risque pour l'environnement principal.",
    difficulty: "Moyen",
  },
  {
    id: "perm-10",
    categorySlug: "permissions",
    question: "Quelle syntaxe dans settings.json autorise spécifiquement les commandes `npm run test` et ses variantes ?",
    options: [
      "\"Bash(npm run test:*)\"",
      "\"Allow(npm test)\"",
      "\"npm:test\"",
      "\"*npm run test*\"",
    ],
    answerIndex: 0,
    explanation: "La syntaxe Bash(commande:*) dans le tableau allow autorise la commande et ses variantes avec arguments.",
    difficulty: "Difficile",
  },
  {
    id: "perm-11",
    categorySlug: "permissions",
    question: "Comment bascule-t-on rapidement entre les modes de permission en session ?",
    options: ["/permissions reset", "Shift+Tab", "Redémarrer claude avec un nouveau flag", "Ctrl+Alt+P"],
    answerIndex: 1,
    explanation: "Shift+Tab permet de changer de mode de permission sans interrompre ni relancer la session.",
    difficulty: "Facile",
  },
  {
    id: "perm-12",
    categorySlug: "permissions",
    question: "Quelle action devrait TOUJOURS rester soumise à confirmation explicite, même en mode auto-accept edits ?",
    options: [
      "La lecture de fichiers",
      "Un git push --force sur une branche partagée",
      "Le lancement de tests unitaires",
      "L'édition d'un fichier de configuration local non partagé",
    ],
    answerIndex: 1,
    explanation: "Les actions difficiles à inverser et affectant un état partagé, comme un force-push, doivent rester confirmées explicitement.",
    difficulty: "Moyen",
  },
];
