import type { QuizQuestion } from "../types";

export const planModeQuestions: QuizQuestion[] = [
  {
    id: "plan-1",
    categorySlug: "plan-mode",
    question: "Quel est l'objectif principal du Plan Mode ?",
    options: [
      "Accélérer l'exécution des tâches simples",
      "Explorer et proposer un plan détaillé sans modifier de fichier, avant validation",
      "Remplacer les tests automatisés",
      "Désactiver totalement les outils de lecture",
    ],
    answerIndex: 1,
    explanation: "Le Plan Mode sert à concevoir avant d'agir : aucune modification n'a lieu avant validation explicite du plan.",
    difficulty: "Facile",
  },
  {
    id: "plan-2",
    categorySlug: "plan-mode",
    question: "Quels outils restent disponibles en Plan Mode ?",
    options: [
      "Aucun outil n'est disponible",
      "Les outils de lecture (Read, Grep, Glob, Bash en lecture)",
      "Uniquement Write",
      "Uniquement les outils MCP",
    ],
    answerIndex: 1,
    explanation: "En Plan Mode, les outils de lecture restent actifs pour permettre l'exploration ; Edit/Write sont désactivés.",
    difficulty: "Moyen",
  },
  {
    id: "plan-3",
    categorySlug: "plan-mode",
    question: "Quel raccourci active le Plan Mode dans le REPL ?",
    options: ["Ctrl+P", "Shift+Tab", "Alt+Enter", "Ctrl+Shift+M"],
    answerIndex: 1,
    explanation: "Shift+Tab permet de basculer entre les modes, y compris vers le Plan Mode.",
    difficulty: "Facile",
  },
  {
    id: "plan-4",
    categorySlug: "plan-mode",
    question: "Pour quel type de tâche le Plan Mode est-il LE MOINS utile ?",
    options: [
      "Une migration de base de données touchant de nombreux fichiers",
      "Une refonte d'architecture impactant plusieurs modules",
      "Une correction de faute de frappe ponctuelle et bien définie",
      "Un changement sur du code critique de production",
    ],
    answerIndex: 2,
    explanation: "Pour une tâche triviale et bien définie, planifier ajoute de la friction sans bénéfice réel.",
    difficulty: "Moyen",
  },
  {
    id: "plan-5",
    categorySlug: "plan-mode",
    question: "Quelle action déclenche le passage du plan validé à l'exécution réelle ?",
    options: ["/compact", "ExitPlanMode (après validation explicite)", "/clear", "Un simple redémarrage de session"],
    answerIndex: 1,
    explanation: "Une fois le plan approuvé, la sortie du Plan Mode (ExitPlanMode) déclenche le passage à l'exécution.",
    difficulty: "Moyen",
  },
  {
    id: "plan-6",
    categorySlug: "plan-mode",
    question: "Quelle est la première étape recommandée du cycle de workflow pour une tâche complexe ?",
    options: ["Exécuter directement", "Explorer le code pertinent", "Vérifier dans le navigateur", "Faire un commit"],
    answerIndex: 1,
    explanation: "Le cycle recommandé est explorer → planifier → exécuter → vérifier ; l'exploration vient en premier.",
    difficulty: "Moyen",
  },
  {
    id: "plan-7",
    categorySlug: "plan-mode",
    question: "Pourquoi est-il risqué d'agir directement sur une tâche ambiguë sans plan préalable ?",
    options: [
      "Cela consomme automatiquement plus de tokens",
      "L'agent peut partir dans une mauvaise direction sans que l'utilisateur puisse intervenir à temps",
      "Cela désactive les hooks de sécurité",
      "Cela empêche toute utilisation ultérieure de Git",
    ],
    answerIndex: 1,
    explanation: "Sans plan validé, une direction erronée peut produire un travail important à défaire, alors qu'un plan permet de corriger le cap avant toute exécution.",
    difficulty: "Moyen",
  },
  {
    id: "plan-8",
    categorySlug: "plan-mode",
    question: "Lors de la dernière étape du cycle (« vérifier »), que recommande-t-on pour un changement UI ?",
    options: [
      "Se fier uniquement aux tests unitaires",
      "Observer réellement le résultat dans un navigateur, pas seulement faire confiance aux tests",
      "Ignorer la vérification si le build passe",
      "Demander uniquement à un sous-agent de confirmer sans observation réelle",
    ],
    answerIndex: 1,
    explanation: "Les tests vérifient la correction du code, pas la correction perçue de la fonctionnalité — il faut observer le résultat réel.",
    difficulty: "Moyen",
  },
  {
    id: "plan-9",
    categorySlug: "plan-mode",
    question: "Un plan proposé peut-il être ajusté avant validation ?",
    options: [
      "Non, il doit être accepté ou rejeté tel quel",
      "Oui, l'utilisateur peut itérer sur le plan avant de l'approuver",
      "Seulement en relançant complètement la session",
      "Seulement si le plan contient moins de 3 étapes",
    ],
    answerIndex: 1,
    explanation: "Le Plan Mode permet d'itérer sur le plan proposé, en demandant des ajustements avant validation finale.",
    difficulty: "Facile",
  },
  {
    id: "plan-10",
    categorySlug: "plan-mode",
    question: "Quel type de contenu un bon plan présente-t-il, au-delà de la liste des étapes ?",
    options: [
      "Uniquement le nombre d'heures estimé",
      "Les fichiers concernés et les éventuels compromis (trade-offs) entre approches possibles",
      "Le code source complet déjà écrit",
      "La liste des contributeurs du projet",
    ],
    answerIndex: 1,
    explanation: "Un bon plan inclut les fichiers impactés et explicite les compromis quand plusieurs approches sont possibles.",
    difficulty: "Moyen",
  },
  {
    id: "plan-11",
    categorySlug: "plan-mode",
    question: "Pourquoi déléguer l'exploration à un sous-agent « Explore » avant le Plan Mode peut être utile ?",
    options: [
      "Cela rend le Plan Mode obsolète",
      "Cela protège le contexte principal en évitant d'y accumuler le détail de la recherche",
      "Cela désactive automatiquement les permissions",
      "Ce n'est jamais recommandé",
    ],
    answerIndex: 1,
    explanation: "Combiner sous-agent d'exploration et Plan Mode permet de garder le contexte principal propre tout en construisant un plan informé.",
    difficulty: "Difficile",
  },
  {
    id: "plan-12",
    categorySlug: "plan-mode",
    question: "Le Plan Mode est-il un mode permanent qu'il faut garder actif tout le temps ?",
    options: [
      "Oui, c'est le mode recommandé pour 100% des tâches",
      "Non, on l'active pour les tâches complexes/ambiguës et on en sort une fois le plan validé",
      "Non, il ne peut être utilisé qu'une seule fois par projet",
      "Oui, c'est le seul mode qui permet d'utiliser Bash",
    ],
    answerIndex: 1,
    explanation: "Le Plan Mode est ponctuel : on l'active pour concevoir, puis on passe à l'exécution une fois le plan validé.",
    difficulty: "Facile",
  },
];
