import type { QuizQuestion } from "../types";

export const skillsQuestions: QuizQuestion[] = [
  {
    id: "skill-1",
    categorySlug: "skills",
    question: "Quel fichier décrit le nom, la description et les instructions d'une Skill ?",
    options: ["README.md", "SKILL.md", "skill.config.json", "manifest.yaml"],
    answerIndex: 1,
    explanation: "SKILL.md contient les métadonnées (nom, description) et les instructions procédurales de la Skill.",
    difficulty: "Facile",
  },
  {
    id: "skill-2",
    categorySlug: "skills",
    question: "Pourquoi les Skills ne sont-elles pas toutes chargées en permanence comme CLAUDE.md ?",
    options: [
      "Pour des raisons de licence",
      "Pour éviter d'alourdir chaque session avec du contexte inutile non pertinent",
      "Parce que Claude Code ne peut gérer qu'une Skill à la fois",
      "Parce que les Skills sont incompatibles avec CLAUDE.md",
    ],
    answerIndex: 1,
    explanation: "Charger seulement les Skills pertinentes permet d'avoir des dizaines de capacités spécialisées sans saturer le contexte.",
    difficulty: "Moyen",
  },
  {
    id: "skill-3",
    categorySlug: "skills",
    question: "Quel élément du SKILL.md est crucial pour une découverte fiable de la Skill par l'agent ?",
    options: [
      "Le nombre de lignes de code dans les scripts associés",
      "La description, qui doit indiquer clairement quand l'utiliser",
      "La date de dernière modification du fichier",
      "Le nom de l'auteur de la Skill",
    ],
    answerIndex: 1,
    explanation: "Une description précise sur le déclencheur (mots-clés, contexte, type de tâche) permet une découverte fiable.",
    difficulty: "Moyen",
  },
  {
    id: "skill-4",
    categorySlug: "skills",
    question: "Que peut contenir un dossier de Skill en plus de SKILL.md ?",
    options: [
      "Uniquement du texte, jamais de scripts",
      "Des scripts et templates associés (ex: scripts/, templates/)",
      "Un sous-agent complet obligatoirement",
      "Une base de données SQLite",
    ],
    answerIndex: 1,
    explanation: "Une Skill packagise SKILL.md avec des ressources comme des scripts ou des templates utilisés par la procédure.",
    difficulty: "Facile",
  },
  {
    id: "skill-5",
    categorySlug: "skills",
    question: "Quelle est la principale différence entre une Skill et un sous-agent ?",
    options: [
      "Aucune différence, ce sont des synonymes",
      "La Skill apporte des instructions chargées à la demande ; le sous-agent est une instance autonome avec son propre contexte et outils",
      "Le sous-agent ne peut jamais utiliser d'outils",
      "La Skill ne peut être utilisée qu'une seule fois par session",
    ],
    answerIndex: 1,
    explanation: "La Skill est un savoir-faire procédural chargé au besoin ; le sous-agent est une délégation complète à une instance autonome.",
    difficulty: "Moyen",
  },
  {
    id: "skill-6",
    categorySlug: "skills",
    question: "Une Skill peut-elle recommander d'utiliser un serveur MCP ou un sous-agent particulier ?",
    options: [
      "Non, ces mécanismes sont totalement indépendants",
      "Oui, ces mécanismes peuvent se combiner",
      "Seulement si la Skill est écrite en JSON",
      "Seulement pour les Skills officielles d'Anthropic",
    ],
    answerIndex: 1,
    explanation: "Skills, sous-agents et MCP sont complémentaires et peuvent se référencer mutuellement dans une même procédure.",
    difficulty: "Moyen",
  },
  {
    id: "skill-7",
    categorySlug: "skills",
    question: "Quelle métadonnée est typiquement présente dans le frontmatter (--- ... ---) d'un SKILL.md ?",
    options: ["name et description", "license et author uniquement", "version de Node.js requise", "Un mot de passe d'accès"],
    answerIndex: 0,
    explanation: "Le frontmatter contient au minimum le nom et la description, utilisés pour la découverte de la Skill.",
    difficulty: "Facile",
  },
  {
    id: "skill-8",
    categorySlug: "skills",
    question:
      "Quelle analogie décrit le mieux le mécanisme de découverte des Skills par Claude Code ?",
    options: [
      "Un appel de fonction, mais pour de la connaissance procédurale plutôt que du code",
      "Une recherche Google classique",
      "Un chargement systématique de tous les fichiers du projet",
      "Une boîte de dialogue de confirmation utilisateur",
    ],
    answerIndex: 0,
    explanation: "Claude Code consulte une liste légère de Skills (nom + description) et charge le contenu complet seulement si pertinent, comme un appel de fonction ciblé.",
    difficulty: "Difficile",
  },
  {
    id: "skill-9",
    categorySlug: "skills",
    question: "Que risque une description de Skill trop vague ou générique ?",
    options: [
      "Rien, la description n'a pas d'impact fonctionnel",
      "La Skill peut ne jamais être déclenchée, ou être déclenchée à tort dans des contextes non pertinents",
      "Le projet ne pourra plus compiler",
      "Cela améliore automatiquement la fiabilité de la détection",
    ],
    answerIndex: 1,
    explanation: "Une description imprécise nuit à la fiabilité de la découverte automatique de la Skill par l'agent.",
    difficulty: "Moyen",
  },
  {
    id: "skill-10",
    categorySlug: "skills",
    question: "Dans quel cas une Skill est-elle particulièrement utile ?",
    options: [
      "Pour stocker des secrets et clés API",
      "Pour documenter une procédure récurrente (ex: déploiement, style de revue de code)",
      "Pour remplacer entièrement le besoin de tests automatisés",
      "Pour gérer l'authentification utilisateur de l'application",
    ],
    answerIndex: 1,
    explanation: "Les Skills excellent à capturer des procédures répétables et spécialisées, invoquées seulement quand pertinent.",
    difficulty: "Facile",
  },
  {
    id: "skill-11",
    categorySlug: "skills",
    question: "Où sont typiquement stockées les Skills personnalisées d'un projet ?",
    options: [".claude/skills/", ".claude/commands/", ".claude/agents/", "skills.json à la racine"],
    answerIndex: 0,
    explanation: "Les Skills personnalisées vivent dans .claude/skills/, chacune dans son propre sous-dossier avec un SKILL.md.",
    difficulty: "Facile",
  },
  {
    id: "skill-12",
    categorySlug: "skills",
    question: "Pourquoi appelle-t-on les Skills des capacités « modulaires » ?",
    options: [
      "Parce qu'elles doivent être réécrites pour chaque projet",
      "Parce qu'elles s'ajoutent/se retirent indépendamment, sans modifier le cœur de l'agent",
      "Parce qu'elles ne fonctionnent que sur des modules npm",
      "Parce qu'elles nécessitent une compilation séparée",
    ],
    answerIndex: 1,
    explanation: "Chaque Skill est un module autonome qu'on peut ajouter, modifier ou retirer sans toucher au reste de la configuration.",
    difficulty: "Moyen",
  },
];
